version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nestjs
  # test-db:
  #   image: postgres:13
  #   ports:
  #     - 5434:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: nestjs

